# Generated by Django 5.0 on 2023-12-26 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('required_magic_power', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Необходимый магический уровень')),
                ('quantity', models.PositiveIntegerField(db_index=True, verbose_name='В наличии')),
                ('image', models.ImageField(upload_to='products', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('categories', models.ManyToManyField(blank=True, related_name='categories_to_product', to='category.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': ('Товар',),
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
            },
        ),
    ]
